$schema: http://json-schema.org/draft-07/schema#
title: kind17
description: Reaction event referencing external content (NIP-25 + NIP-73)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 17
      content:
        type: string
        description: Reaction marker such as "+", "-", or an emoji
      tags:
        type: array
        minItems: 1
        items:
          allOf:
            - $ref: "@/tag.yaml"
            - if:
                type: array
                minItems: 1
                items:
                  - const: "emoji"
              then:
                $ref: "@/tag/emoji.yaml"
        allOf:
          - contains:
              $ref: "@/tag/external-content-k.yaml"
            errorMessage:
              contains: "tags must include at least one k tag describing the external content type"
          - contains:
              $ref: "@/tag/external-content-i.yaml"
            errorMessage:
              contains: "tags must include at least one i tag referencing the external content"
    required:
      - kind
      - tags
