$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "polltype"
      - type: string
        enum:
          - singlechoice
          - multiplechoice
    additionalItems: false
    errorMessage:
      items: "polltype tag must be ['polltype', 'singlechoice'|'multiplechoice']"
