$schema: http://json-schema.org/draft-07/schema#
title: kind10063
allOf: 
  - $ref: "@/note.yaml"
  - type: object
    properties: 
      kind:
        const: 10063
      tags: 
        type: array
        items: 
          $ref: "@/tag/server.yaml"
        additionalItems: false
        minItems: 1
        errorMessage:
          type: "tags must be an array of server tags"
          minItems: "tags array must have at least one server tag"
          additionalItems: "server lists must only include server tags"
    required:
      - tags
