$id: 'https://schemata.nostr.watch/message/relay/eose'
type: "array"
description: "End Of Subscription Event"
items: 
- const: "EOSE"
- type: "string"
  description: "The id of the subscription that was successfully fulfilled"
minItems: 2
maxItems: 2