$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "lnurl"
      - type: string
        pattern: '^lnurl[0-9a-z]+$'
        description: "Bech32-encoded lnurl with 'lnurl' prefix"
    additionalItems: false

