$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "relay"
      - type: string
        pattern: '^(ws://|wss://).+$'
    additionalItems: true
    errorMessage:
      items: "relay tag must start with 'relay' followed by a valid ws or wss URL"
