$schema: "https://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "context"
      - type: string
        description: "Text surrounding the highlight to provide context"
    additionalItems: false

