$schema: http://json-schema.org/draft-07/schema#
title: kind31924
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 31924
      tags:
        type: array
        allOf:
          # required: d
          - contains:
              $ref: "@/tag/d.yaml"
          # required: title
          - contains:
              $ref: "@/tag/title.yaml"
    # Optional tags: if present, enforce shape
    allOf:
      # references to 31922/31923 events via a
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "a"
        then:
          properties:
            tags:
              contains:
                allOf:
                  - $ref: "@/tag.yaml"
                  - type: array
                    minItems: 2
                    items:
                      - const: "a"
                      - type: string
                        pattern: '^(31922|31923):[a-f0-9]{64}:.+$'
                    additionalItems: true
      # optional summary, image
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "summary"
        then:
          properties:
            tags:
              contains:
                $ref: "@/tag/summary.yaml"
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "image"
        then:
          properties:
            tags:
              contains:
                $ref: "@/tag/image.yaml"
    additionalProperties: true
