$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Nonce required alongside the decryption key"
    minItems: 2
    items:
      - const: "decryption-nonce"
      - type: string
        minLength: 1
    additionalItems: false
