$schema: http://json-schema.org/draft-07/schema#
title: kind10015
description: Interests List (NIP-51)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 10015
    required:
      - kind
