$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "relays"
      - type: string
        pattern: '^(ws://|wss://).+$'
    additionalItems: true

