$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "cmd"
      - type: string
        enum: ["REQ", "COUNT"]
    additionalItems: false
    errorMessage:
      minItems: "cmd tag must have at least 2 elements"
