$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "pinned"
      - type: string
        pattern: '^[a-f0-9]{64}$'
    additionalItems: true

