$schema: http://json-schema.org/draft-07/schema#
title: kind30313
description: Meeting Room Event (Scheduled/Ongoing meeting, NIP-53)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30313
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
            errorMessage:
              contains: "tags must include a d tag"
          - contains:
              $ref: "@/tag/a-room.yaml"
            errorMessage:
              contains: "tags must include an a tag referencing a room (kind 30312)"
          - contains:
              $ref: "@/tag/title.yaml"
            errorMessage:
              contains: "tags must include a title tag"
          - contains:
              $ref: "@/tag/starts.yaml"
            errorMessage:
              contains: "tags must include a starts tag"
          - contains:
              $ref: "@/tag/status-live.yaml"
            errorMessage:
              contains: "tags must include a status tag"
    required:
      - kind
      - tags

