$schema: https://json-schema.org/draft-07/schema#
title: kind30313
description: Meeting Room Event (Scheduled/Ongoing meeting, NIP-53)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30313
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
          - contains:
              $ref: "@/tag/a-room.yaml"
          - contains:
              $ref: "@/tag/title.yaml"
          - contains:
              $ref: "@/tag/starts.yaml"
          - contains:
              $ref: "@/tag/status-live.yaml"
        errorMessage:
          contains: "tags must include required tags: d, a (room reference), title, starts, status"
    required:
      - kind
      - tags

