$schema: http://json-schema.org/draft-07/schema#
title: kind10102
description: Good Wiki Relays List (NIP-51)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 10102
    required:
      - kind
