$schema: https://json-schema.org/draft/2020-12/schema
title: kind30024
description: Long-form Content Draft, NIP-23
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30024
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
        errorMessage:
          contains: "tags must include required tag: d"
    required:
      - kind
      - tags
