$schema: http://json-schema.org/draft-07/schema#
title: kind30024
description: Long-form Content Draft, NIP-23
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30024
    required:
      - kind

