$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "amount"
      - type: string
        pattern: '^[0-9]+$'
        description: "Amount in millisats, as a decimal string"
    additionalItems: false

