$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "request"
      - type: string
        minLength: 1
        description: "JSON-encoded original job request event"
    additionalItems: false
