$schema: http://json-schema.org/draft-07/schema#
title: kind443
description: MLS KeyPackage Event (NIP-EE)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 443
      content:
        type: string
        pattern: '^(?:[0-9A-Fa-f]{2})+$'
        errorMessage: "content must be a hex-encoded MLS KeyPackageBundle"
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/mls_protocol_version.yaml"
          - contains:
              $ref: "@/tag/ciphersuite.yaml"
          - contains:
              $ref: "@/tag/extensions.yaml"
        errorMessage:
          contains: "tags must include mls_protocol_version, ciphersuite, and extensions tags"
    required:
      - kind
      - content
      - tags
