$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "pubkey"
      - type: string
        pattern: '^02[0-9a-fA-F]{64}$'
    additionalItems: false
