$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "method"
      - type: string
        pattern: '^[A-Z]+$'
    additionalItems: false
