$schema: "http://json-schema.org/draft-07/schema#"
title: kind22242
description: Ephemeral authentication event defined by NIP-42
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 22242
        description: "Kind 22242 identifies an authentication event"
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/auth-relay.yaml"
            errorMessage:
              contains: "tags must include a relay tag identifying the authenticating relay"
          - contains:
              $ref: "@/tag/challenge.yaml"
            errorMessage:
              contains: "tags must include a challenge tag with the relay-provided challenge string"
    required:
      - kind
      - tags
