$schema: http://json-schema.org/draft-07/schema#
title: kind7374
description: "Quote state event defined by NIP-60"
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 7374
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/expiration.yaml"
          - contains:
              $ref: "@/tag/mint.yaml"
    required:
      - tags
