$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 3
    items:
      - const: "option"
      - type: string
        pattern: '^[A-Za-z0-9]+$'
      - type: string
        minLength: 1
    additionalItems: true
    errorMessage:
      minItems: "option tag must provide an identifier and label"
      items: "option tag must start with 'option', followed by an alphanumeric id and a non-empty label"
