$schema: http://json-schema.org/draft-07/schema#
title: kind31989
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 31989
      tags:
        allOf:
          # At least one ["d", <supported-event-kind>]
          - contains:
              allOf:
                - $ref: "@/tag/d.yaml"
          # At least one ["a", "31990:<pubkey>:<identifier>", <relay?>, <platform?>]
          - contains:
              allOf:
                - $ref: "@/tag/a.yaml"
