$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 4
    items:
      - const: "client"
      - type: string
        minLength: 1
      - type: string
        pattern: '^[a-f0-9]{64}$'
      - type: string
        pattern: '^(ws://|wss://).+$'
    additionalItems: false
