$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Encryption algorithm used for the attached file"
    minItems: 2
    items:
      - const: "encryption-algorithm"
      - type: string
        enum:
          - "aes-gcm"
    additionalItems: false
