$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    prefixItems:
      - const: "relay"
      - type: string
        pattern: '^(ws://|wss://).+$'
    items: false
