$schema: http://json-schema.org/draft-07/schema#
title: kind9007
description: "Create group event defined by NIP-29"
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 9007
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/h.yaml"
            errorMessage:
              contains: "tags must include an h tag with a group identifier"
    required:
      - tags
