$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "relay"
      - type: string
        pattern: '^(ws://|wss://).+$'
    additionalItems: true
    errorMessage:
      pattern: "relay tag value must be a valid ws:// or wss:// URL"
