$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag/relay.yaml"
  - type: array
    description: "Relay endpoint that issued the NIP-42 authentication challenge"
    errorMessage: "relay tag must include a valid ws or wss URL and cannot contain extra fields"
