$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Size of the encrypted file in bytes"
    minItems: 2
    items:
      - const: "size"
      - type: string
        pattern: '^[0-9]+$'
    additionalItems: false
