$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "p"
      - $ref: "@/secp256k1.yaml"
      - title: 'petname'
        type: string
    additionalItems: false
