$schema: https://json-schema.org/draft/2020-12/schema
title: nip05Identifier
description: Internet Identifier for NIP-05 (email-like, case-insensitive local-part)
type: string
# Allows "_@domain" (root identifier) or "<local-part>@<domain>"
# local-part: a-z A-Z 0-9 _ . -
# domain: labels with a-z A-Z 0-9 - separated by dots, ending with a TLD (>=2 letters). Supports punycode (xn--)
pattern: ^(([_A-Za-z0-9.-]+)|_)@[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?)+$

