$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Reference to the root patch or issue event"
    minItems: 4
    maxItems: 4
    items:
      - const: "e"
      - type: string
        pattern: '^[a-f0-9]{64}$'
      - anyOf:
          - type: string
            const: ""
          - type: string
            pattern: '^(ws://|wss://).+$'
      - const: "root"
    additionalItems: false
