$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "network"
      - type: string
        minLength: 1
        description: "Bitcoin network (e.g. mainnet, testnet, signet)"
    additionalItems: false
    errorMessage:
      minItems: "network tag must have at least 2 elements"
