$schema: http://json-schema.org/draft-07/schema#
title: kind31925
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 31925
      tags:
        type: array
        allOf:
          # required: a (coordinates must reference 31922 or 31923)
          - contains:
              allOf:
                - $ref: "@/tag.yaml"
                - type: array
                  minItems: 2
                  items:
                    - const: "a"
                    - type: string
                      pattern: '^(31922|31923):[a-f0-9]{64}:.+$'
                  additionalItems: true
          # required: d
          - contains:
              $ref: "@/tag/d.yaml"
          # required: status
          - contains:
              $ref: "@/tag/status.yaml"
    allOf:
      # If status is 'declined', fb must not be present
      - not:
          allOf:
            - properties:
                tags:
                  contains:
                    type: array
                    minItems: 2
                    items:
                      - const: "status"
                      - type: string
                        const: "declined"
            - properties:
                tags:
                  contains:
                    type: array
                    minItems: 1
                    items:
                      - const: "fb"
      # If fb present, enforce enum
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "fb"
        then:
          properties:
            tags:
              contains:
                $ref: "@/tag/fb.yaml"
      # If e present, enforce tag shape
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "e"
        then:
          properties:
            tags:
              contains:
                $ref: "@/tag/e.yaml"
      # If p present, enforce tag shape
      - if:
          properties:
            tags:
              contains:
                type: array
                minItems: 1
                items:
                  - const: "p"
        then:
          properties:
            tags:
              contains:
                $ref: "@/tag/p.yaml"
    additionalProperties: true
