$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "published_at"
      - type: string
        pattern: "^[1-9][0-9]{9}$"
    additionalItems: true

