$schema: "https://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "streaming"
      - type: string
        pattern: '^(https?://|rtmp://|ws://|wss://).+$'
    additionalItems: true

