$schema: "http://json-schema.org/draft-07/schema#"
title: externalContentTypeTag
description: External content type identifier tag (NIP-73)
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 3
    items:
      - const: "k"
      - type: string
        minLength: 1
        pattern: "^[A-Za-z0-9][A-Za-z0-9._+-]*(?::[A-Za-z0-9][A-Za-z0-9._+-]*)*$"
        description: Type identifier for the external resource
      - type: string
        minLength: 1
        description: Optional subtype or hint for the external resource
    errorMessage:
      minItems: "k tag must be ['k', <type>, ...]"
