$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "endpoint"
      - type: string
        pattern: '^(https?://).+$'
    additionalItems: true

