$schema: http://json-schema.org/draft-07/schema#
title: kind3
type: object
properties:
  content:
    type: string
  created_at:
    type: integer
  id:
    $ref: "#/$defs/secp256k1"
  kind:
    type: number
    const: 3
  pubkey:
    $ref: "#/$defs/secp256k1"
  sig:
    type: string
  tags:
    type: array
    items:
      type: array
      minItems: 2
      maxItems: 2
      items: 
        - type: string
          const: "p"
        - $ref: "#/$defs/secp256k1"
      additionalItems: false
required:
  - content
  - created_at
  - id
  - kind
  - pubkey
  - sig
  - tags
additionalProperties: false
$defs:
  secp256k1: 
    type: string
    pattern: "^[a-f0-9]{64}$"
