---
$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  content:
    type: string
  created_at:
    type: integer
  id:
    $ref: "#/$defs/secp256k1"
  kind:
    type: integer
  pubkey:
    $ref: "#/$defs/secp256k1"
  sig:
    type: string
  tags:
    type: array
    items:
    - type: array
      prefixItems:
        - type: string
        - type: "#/$defs/secp256k1"
required:
  - content
  - created_at
  - id
  - kind
  - pubkey
  - sig
  - tags
additionalProperties: false

$defs:
  secp256k1: 
    type: string
    pattern: "^[a-f0-9]{64}$"
