$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Earliest unique commit identifier"
    minItems: 3
    maxItems: 3
    items:
      - const: "r"
      - type: string
        pattern: '^[a-f0-9]{40}$'
      - const: "euc"
    additionalItems: false
