$schema: "http://json-schema.org/draft-07/schema#"
title: emojiTag
description: Custom emoji resource reference for reactions (NIP-25 / NIP-30)
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 3
    maxItems: 3
    items:
      - const: "emoji"
      - type: string
        minLength: 1
        pattern: "^[0-9A-Za-z_:+-]+$"
        description: Shortcode identifying the emoji without surrounding colons
      - type: string
        pattern: "^https?://.+"
        description: HTTPS URL pointing to the emoji image
    errorMessage:
      minItems: "emoji tag must contain ['emoji', <shortcode>, <https url>]"
      maxItems: "emoji tag must contain ['emoji', <shortcode>, <https url>]"
