$schema: https://json-schema.org/draft-07/schema#
title: kind16
description: Generic repost (NIP-18) for reposting events other than kind-1
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 16
      content:
        type: string
        description: Stringified JSON of the reposted event (MAY be empty).
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/k.yaml"
        errorMessage:
          contains: "tags must include a k tag with the reposted kind as a string"
    required:
      - kind
      - tags

