$id: 'https://schemata.nostr.watch/message/relay/closed'
type: "array"
items: 
- const: "CLOSED"
- type: "string"
  description: "The id of the subscription that was closed"
  errorMessage: "subscription id must be a string and should be unique."
- type: "string"
  description: "A response message"
  errorMessage: "response message must be a string that follows the format: '{code}: {message}'"
  pattern: "^[a-zA-Z0-9_-]+: .+"
minItems: 3
maxItems: 3
additionalItems: false