$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "mls_protocol_version"
      - type: string
        pattern: '^[0-9]+(\.[0-9]+){1,2}$'
    errorMessage:
      pattern: "mls_protocol_version tag value must be a semantic version like '1.0'"
    additionalItems: false
