$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Git clone endpoints"
    minItems: 2
    items:
      - const: "clone"
      - type: string
        pattern: '^(([a-z][a-z0-9+\.-]*://)|git@)[^\s]+$'
    additionalItems:
      type: string
      pattern: '^(([a-z][a-z0-9+\.-]*://)|git@)[^\s]+$'
