$schema: "https://json-schema.org/draft-07/schema#"
title: kind30023
description: NIP-23 Long-form Content (published)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30023
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
        errorMessage:
          contains: "tags must include required tag: d"
    required:
      - kind
      - tags

