$schema: http://json-schema.org/draft-07/schema#
title: kind30023
description: Long-form Content (Article), NIP-23
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30023
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
            errorMessage:
              contains: "tags must include a d tag"
          - contains:
              $ref: "@/tag/title.yaml"
            errorMessage:
              contains: "tags must include a title tag"
    required:
      - kind
      - tags
