$schema: http://json-schema.org/draft-07/schema#
title: kind4
description: Encrypted Direct Message (NIP-04)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 4
      content:
        type: string
        pattern: "^[A-Za-z0-9+/]+={0,2}\\?iv=[A-Za-z0-9+/]+={0,2}$"
        errorMessage: "content must be '<ciphertext>?iv=<initialization_vector>' where both values are base64"
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        allOf:
          - contains:
              $ref: "@/tag/p.yaml"
          - anyOf:
              - not:
                  contains:
                    type: array
                    minItems: 1
                    items:
                      - const: "e"
              - contains:
                  type: array
                  minItems: 2
                  items:
                    - const: "e"
                    - type: string
                      pattern: "^[a-f0-9]{64}$"
        errorMessage:
          contains: "tags must include a p tag identifying the intended recipient"
    required:
      - kind
      - content
      - tags
