$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Key required to decrypt the encrypted file"
    minItems: 2
    items:
      - const: "decryption-key"
      - type: string
        minLength: 1
    additionalItems: false
