$schema: "http://json-schema.org/draft-07/schema#"
title: MLS Ciphersuite
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "mls_ciphersuite"
      - type: string
        pattern: "^0x[0-9a-f]{4}$"
        description: "MLS ciphersuite identifier in 0xXXXX format"
    additionalItems: false
