$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Authentication challenge provided by the relay"
    minItems: 2
    items:
      - const: "challenge"
      - type: string
        minLength: 1
    additionalItems: false
    errorMessage:
      minItems: "challenge tag must include the relay-provided string"
      additionalItems: "challenge tag accepts only the name and challenge value"
