$schema: https://json-schema.org/draft/2020-12/schema
title: kind31990
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 31990
      tags:
        allOf:
          # At least one ["d", <random-id>]
          - contains:
              allOf:
                - $ref: "@/tag/d.yaml"
          # At least one ["k", <supported-event-kind>]
          - contains:
              allOf:
                - $ref: "@/tag/k.yaml"
