$schema: http://json-schema.org/draft-07/schema#
title: kind9002
description: "Edit group metadata event defined by NIP-29"
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 9002
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/h.yaml"
    required:
      - tags
