$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Image dimensions in the form <width>x<height>"
    minItems: 2
    items:
      - const: "dim"
      - type: string
        pattern: '^\d+x\d+$'
    additionalItems: false
