$schema: https://json-schema.org/draft-07/schema#
title: kind30311
description: Live Streaming Event (addressable, NIP-53)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 30311
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        contains:
          $ref: "@/tag/d.yaml"
        errorMessage:
          contains: "tags must include at least one d tag (unique identifier)"
    required:
      - kind
      - tags

