$schema: http://json-schema.org/draft-07/schema#
title: kind10051
description: Marmot KeyPackage relay list event (MIP-00)
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 10051
        description: "Kind number for publishing relays that host Marmot KeyPackages"
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        minItems: 1
        contains:
          $ref: "@/tag/relay.yaml"
        errorMessage:
          contains: "tags must include at least one relay tag identifying a KeyPackage relay"
    required:
      - kind
      - tags
