$id: 'https://schemata.nostr.watch/note/tag/k'
$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "k"
      - type: string
        pattern: '^\d+$'
    additionalItems: false