$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Checksum of the encrypted file"
    minItems: 2
    items:
      - const: "x"
      - type: string
        pattern: '^[a-f0-9]{64}$'
    additionalItems: false
