$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "client"
      - type: string
        minLength: 1
        description: "Client display name or identifier"
    additionalItems:
      type: string
