$schema: http://json-schema.org/draft-07/schema#
title: kind34236
description: "Updatable vertical video event defined by NIP-71"
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 34236
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/d.yaml"
          - contains:
              $ref: "@/tag/title.yaml"
          - contains:
              $ref: "nips/nip-71/tag/imeta/schema.yaml"
    required:
      - tags
    additionalProperties: true
