---
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  content:
    type: string
  created_at:
    type: integer
  id:
    $ref: "@/secp256k1.yaml"
  kind:
    type: integer
  pubkey:
    $ref: "@/secp256k1.yaml"
  sig:
    type: string
  tags:
    type: array
    items:
    - $ref: "@/tag.yaml"
      
required:
- content
- created_at
- id
- kind
- pubkey
- sig
- tags