---
"$schema": http://json-schema.org/draft-07/schema#
type: object
properties:
  content:
    type: string
  created_at:
    type: integer
  id:
    $ref: "nips/nipless/secp256k1/schema.yaml"
  kind:
    type: integer
  pubkey:
    $ref: "nips/nipless/secp256k1/schema.yaml"
  sig:
    type: string
  tags:
    type: array
    items:
    - $ref: "nips/nip-01/tag/schema.yaml"
      
required:
- content
- created_at
- id
- kind
- pubkey
- sig
- tags