$schema: http://json-schema.org/draft-07/schema#
title: kind9321
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 9321
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/proof.yaml"
            errorMessage:
              contains: "tags must include a proof tag with P2PK-locked tokens"
          - contains:
              $ref: "@/tag/u.yaml"
            errorMessage:
              contains: "tags must include a u tag identifying the mint"
          - contains:
              $ref: "@/tag/p.yaml"
            errorMessage:
              contains: "tags must include a p tag identifying the recipient"
    required:
      - tags
