$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 3
    items:
      - const: "p"
      - $ref: "@/secp256k1.yaml"
      - type: string
        enum: [nudity, malware, profanity, illegal, spam, impersonation, other]
    additionalItems: true

