$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "extensions"
      - type: string
        pattern: "^0x[0-9a-fA-F]{4}$"
        description: "MLS extension identifier"
    additionalItems:
      type: string
      pattern: "^0x[0-9a-fA-F]{4}$"
