$schema: "https://json-schema.org/draft/2020-12/schema"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "comment"
      - type: string
        description: "A comment for quote highlight rendering"
    additionalItems: false

