$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    items:
      - const: "comment"
      - type: string
        description: "A comment for quote highlight rendering"
    additionalItems: false

