$schema: http://json-schema.org/draft-07/schema#
title: kind17375
description: "Wallet event defined by NIP-60"
allOf:
  - $ref: "@/note.yaml"
  - type: object
    properties:
      kind:
        const: 17375
      tags:
        type: array
        items:
          $ref: "@/tag.yaml"
        allOf:
          - contains:
              $ref: "@/tag/mint.yaml"
            errorMessage:
              contains: "tags must include a mint tag"
    required:
      - tags
