$schema: "http://json-schema.org/draft-07/schema#"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    description: "Thumbnail URL for the encrypted media"
    minItems: 2
    items:
      - const: "thumb"
      - type: string
        format: uri
    additionalItems: false
